### ISSUE TITLE
Use an array?

### ISSUE THREAD

**Issue by Jacob-C-Smith** [SpaceDoddyssey/IGCLightDark#2]
Instead of branching many times [here](https://github.com/SpaceDoddyssey/IGCLightDark/blob/fd9e62040373ee50ec85b09cef78ccae87bd4a3f/Assets/Scripts/GameState.cs#LL23C1-L37C10) with a switch, why don't you use an array. You could index it using ```Mathf.Abs(polarity)```. That way the only branch is the default case. Something like...
```cs
// Class data
float[] polarity2Damage = new float[] { 0.0f, 0.5f, 0.75f, 1.25f, 2.0f };

// ...

public float GetDamageModifier()
{

    // Compute the (possible) index
    int polarityIndex = (int) Mathf.Abs(polarity);

    // Return the damage modifier, if the bounds check is okay
    return ( polarityIndex <= 4 && polarityIndex >= 0) ? polarity2Damage[polarityIndex] : 1.0f;
}

```

**Comment by halfcourtyeet** [comment]
Yeah, I should have done this a while ago. Maybe if I go back and fix the source up.
